project:
  type: website
  output-dir: _temp_site
  render:
    - "*.qmd"
  resources:
    - "img/**/*"
    - "site_libs/**/*"
  preview:
    port: 3000
    browser: true

website:
  title: "Über Gewissheit - Wittgenstein ausgelegt"
  navbar:
    left:
      - href: index.qmd
        text: Startseite
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Überblick"
        contents:
          - index.qmd
      - section: "Manuskript und Editionsgeschichte"
        contents:
          - wittgenstein-werke.qmd
          - faksimile.qmd
          - ueber-gewissheit.qmd
      - section: "Seminar-Reportagen"
        contents:
          - sitzung1.qmd
      - section: "Anhang"
        contents:
          - references.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-copy: true
    link-external-icon: true
    link-external-newwindow: true 